version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - postgres:/var/lib/postrgesql/data
  api:
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/botson?schema=public"
    container_name: botson_api
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
  queue:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=miniominio13
      - MINIO_REGION_NAME=us-east-1
    command: server --console-address ":9001" /data
volumes:
  postgres:
  minio: