version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - postgres:/var/lib/postrgesql/data
  api:
    container_name: botson_api
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  postgres:
