name: build
on:
  push:
    branches:
      - main
      - dev
      - ci-*
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - name: "Build image"
        run: docker build .