name: build
on:
  push:
    branches:
      - main
      - dev
      - ci-*
  pull_request:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: "nomad"
    steps:
      - uses: actions/checkout@v2
      - name: "Build image"
        run: docker build . --tag api:$(git rev-parse --short "$GITHUB_SHA")